Make SSL 0.9.8 optional in ulinux build

diff --git a/Unix/configure b/Unix/configure
--- a/Unix/configure
+++ b/Unix/configure
@@ -316,6 +316,11 @@ do
         disable_makefile_gen=1
         ;;
 
+    --disable-ssl-0.9.8)
+        disable_ssl_0_9_8=1
+        ;;
+
+
     *)
         echo "$0: unknown option:  $opt"
         exit 1
@@ -413,7 +418,8 @@ OPTIONS:
                             builds of OMI, including ULINUX as necessary
     --disable-makefile-gen  Disable Makefile generation (used internally for
                             universal builds)
-
+    --disable-ssl-0.9.8     When building with --enable-ulinux, skip the ssl
+                            0.9.8 build and only do ssl 1.0.0.
 EOF
     exit 0
 fi
@@ -494,11 +500,13 @@ if [ "$enable_ulinux" = "1" ]; then
     openssl100_cflags=`PKG_CONFIG_PATH=$openssl100_libdir/pkgconfig $pkgconfig --cflags openssl`
     openssl100_libs=`PKG_CONFIG_PATH=$openssl100_libdir/pkgconfig $pkgconfig --libs openssl`
 
-    echo "checking for local installation of openssl version 0.9.8 on system ..."
-    if [ ! -d "$openssl098_dir" ]; then
-        echo "did not find ${openssl098_dir}, which is required."
-        echo "you must install a local copy of openssl version 0.9.8 to build successfully."
-        exit 1
+    if [ "$disable_ssl_0_9_8" != "1" ]; then
+        echo "checking for local installation of openssl version 0.9.8 on system ..."
+        if [ ! -d "$openssl098_dir" ]; then
+            echo "did not find ${openssl098_dir}, which is required."
+            echo "you must install a local copy of openssl version 0.9.8 to build successfully."
+            exit 1
+        fi
     fi
 
     echo "checking for local installation of openssl version 1.0.0 on system ..."
@@ -2463,17 +2471,20 @@ __ROOT=$root
 export OUTPUTDIR=$outputdir
 export ROOT=$root
 export ENABLE_ULINUX=$enable_ulinux
+export DISABLE_SSL_0_9_8=$disable_ssl_0_9_8
 
 OMI_CONFIGURE_QUALS=--enable-microsoft --disable-makefile-gen
 
 all:
 ifeq (\$(ENABLE_ULINUX),1)
 
+ifneq (\$(DISABLE_SSL_0_9_8),1)
 	@echo '========================= Performing Building OMI (SSL 0.9.8)'
 
 	@echo Running: ./configure \$(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_0.9.8 --opensslcflags="${openssl098_cflags}" --openssllibs="${openssl098_libs}" --openssllibdir="${openssl098_libdir}"; \
 	./configure \$(OMI_CONFIGURE_QUALS) --outputdirname=output_openssl_0.9.8 --opensslcflags="${openssl098_cflags}" --openssllibs="${openssl098_libs}" --openssllibdir="${openssl098_libdir}"; \
 	( cd \$(__ROOT); OUTPUTDIR=${root}/output_openssl_0.9.8; \$(MAKE) -f build.mak )
+endif
 
 	@echo '========================= Performing Building OMI (SSL 1.0.0)'
 
